### ISSUE TITLE
Add active_test=False by default to searchid?

### ISSUE THREAD

**Issue by Yajo** [Tardo/OdooTerminal#14]
See this session:

![2020-05-14_12-46](https://user-images.githubusercontent.com/973709/81930844-07d80800-95e1-11ea-93f9-380578c3bba6.png)

It would have made sense to me that searchid found the record even when inactive.

Also coming from Odoo world, maybe "read" is a better name for searchid, given that's the RPC name of the method. But that's not important.

**Comment by Tardo** [comment]
Thanks for report!
For the 'active' case, you can use the following command: ```context write "{'active_test': false}"```
If you want have it on all sessions you can add it on preferences (This option is not currently working, the fix is coming :B):
![ot_options](https://user-images.githubusercontent.com/731270/82717578-59e1f300-9c9d-11ea-8483-662086716008.png)

This is really interesting to know, i will update the readme with this useful information! Thanks!

**Comment by Tardo** [comment]
Renamed the 'search' and 'searchid' commands to 'read' and 'readid'. Now old names are deprecated (not deleted)

**Comment by Yajo** [comment]
I still think that context should be enabled by default for `readid`, given you're explicitly saying the ID (so IMHO it should find it if it exists, not just if it is active).

But well, not a real problem as I'm gonna add those settings you said. Thanks!

**Comment by Tardo** [comment]
Yeah... old comments are invalidated xD please, read the edited version.

**Comment by Tardo** [comment]
Fixed here https://github.com/Tardo/OdooTerminal/pull/15
