### ISSUE TITLE
[BUG] ALT+T opens browser menu "tools" in firefox

### ISSUE THREAD

**Issue by mohamedhagag** [Tardo/OdooTerminal#69]
ALT+T opens browser menu "tools" in firefox
Can we make the key shortcut configurable ?!

**Comment by Tardo** [comment]
omg... thx for report! ummmm any idea for a good shortcut to use?

**Comment by mohamedhagag** [comment]
CTRL + , 
comma not period ;)
like vscode settings

**Comment by mads-vkd** [comment]
Might have missed it, but what was the reason for deprecating CTRL+1? :)

Wouldn't mind it being a somewhat configurable what shortcut you could use just for bringing up the terminal specifically - obviously I might just be too used to the old one ^^;
But ALT also engages Odoo shortcuts, which makes it a bit.. unnerving, at times, to use ALT as the new keyhold.

Same thing with adding a verification step to uninstalling modules; good practice to do generally speaking.
Conversely, personally I don't feel the need for it, but considering the above, I wouldn't suggest a complete removal of it, either. 
Perhaps make it a togglable option to have the added step or not? :)

**Comment by Tardo** [comment]
The main reason for removing it has been that on pages where the terminal cannot be loaded, CTRL+1 switches to the first tab of the browser.
I realize that the change is a nuisance, but nothing that time will not fix in the short term.

I hope to have the changes ready today and that everyone can set this shortcut as want and by default I think it's correct to leave "CTRL + ,". I apologize for this "dance" of shortcuts.

For the "uninstall" command, I know people who don't use this command from the terminal because they don't know that they are uninstalling. Currently you can use "-f" to skip questions (uninstall module -f) :). Having an option to disable this feature may lead to problems in some environments. 
If you want, you can create an alias: `alias -n remove -c "uninstall -f -m $1"`.

**Comment by mohamedhagag** [comment]
> Same thing with adding a verification step to uninstalling modules; good practice to do generally speaking. Conversely, personally I don't feel the need for it, but considering the above, I wouldn't suggest a complete removal of it, either. Perhaps make it a togglable option to have the added step or not? :)



the uninstall question is a very nice - I used to just type uninstall MODULE and get all other modules removed by accident ;( .

**Comment by mads-vkd** [comment]
> The main reason for removing it has been that on pages where the terminal cannot be loaded, CTRL+1 switches to the first tab of the browser. I realize that the change is a nuisance, but nothing that time will not fix in the short term.
> 
> I hope to have the changes ready today and that everyone can set this shortcut as want and by default I think it's correct to leave "CTRL + ,". I apologize for this "dance" of shortcuts.
> 
> For the "uninstall" command, I know people who don't use this command from the terminal because they don't know what they are uninstalling. Currently you can use "-f" to skip questions (uninstall module -f) :). Having an option to disable this feature may lead to problems in some environments. If you want, you can create an alias: `alias -n remove -c "uninstall -f -m $1"`.

Ah, fair enough :)
Yeah, CTRL + , might be better, in that case - because ALT+T is also the shortcut for, for example, the Action menu on some Odoo versions (12, I believe) :)
