### ISSUE TITLE
[BUG] calling `write` doesn't execute a write

### ISSUE THREAD

**Issue by yajo** [Tardo/OdooTerminal#84]
First of all, check that you are using the latest version.

**Basic Info. (please complete the following information):**
 - Odoo version: 15.0
 - Browser: firefox
 - Command: `write hr.attendance 1446 'check_out="2022-10-25 12:50"'`

**Describe the bug**
With this command I was able to fix my forgotten check in/out times. But since v9, it seems that `write` does not call the server.

**Expected behavior**
Execute write operation.

**Additional context**
Used to work fine. I was able to do the same with recordset and commit though.

**Comment by Tardo** [comment]
Yes, "SimpleJSON" was removed... I've removed it because it no longer provides an advantage in terms of the number of characters that must be used to define a dictionary.

Now the interpreter doesn't use 'JSON.parse' so... no more json constrains: don't need quoted keys or use quotes when define the dictionary using spaces

- Old: `write hr.attendance 1446 "{'check_out': "2022-10-25 12:50"}"`
- New: `write hr.attendance 1446 {check_out: "2022-10-25 12:50"}`

**Comment by yajo** [comment]
ah ok! thanks then :)
